services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4871:4871"
    restart: always
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6731:6731"
    restart: always
