<script>
  let {
    width = 30,
    height = 30,
    opacity = 100,
    class: className = null,
  } = $props();
</script>

<svg
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 100 100"
  preserveAspectRatio="xMidYMid"
  {width}
  {height}
  style="shape-rendering: auto; display: block; background: rgb(255, 255, 255); opacity: {opacity /
    100};"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  class={className}
  ><g
    ><g transform="rotate(0 50 50)">
      <rect fill="#000000" height="12" width="5" ry="0" rx="0" y="27" x="47.5">
        <animate
          repeatCount="indefinite"
          begin="-0.9090909090909091s"
          dur="1s"
          keyTimes="0;1"
          values="1;0"
          attributeName="opacity"
        ></animate>
      </rect>
    </g><g transform="rotate(32.72727272727273 50 50)">
      <rect fill="#000000" height="12" width="5" ry="0" rx="0" y="27" x="47.5">
        <animate
          repeatCount="indefinite"
          begin="-0.8181818181818182s"
          dur="1s"
          keyTimes="0;1"
          values="1;0"
          attributeName="opacity"
        ></animate>
      </rect>
    </g><g transform="rotate(65.45454545454545 50 50)">
      <rect fill="#000000" height="12" width="5" ry="0" rx="0" y="27" x="47.5">
        <animate
          repeatCount="indefinite"
          begin="-0.7272727272727273s"
          dur="1s"
          keyTimes="0;1"
          values="1;0"
          attributeName="opacity"
        ></animate>
      </rect>
    </g><g transform="rotate(98.18181818181819 50 50)">
      <rect fill="#000000" height="12" width="5" ry="0" rx="0" y="27" x="47.5">
        <animate
          repeatCount="indefinite"
          begin="-0.6363636363636364s"
          dur="1s"
          keyTimes="0;1"
          values="1;0"
          attributeName="opacity"
        ></animate>
      </rect>
    </g><g transform="rotate(130.9090909090909 50 50)">
      <rect fill="#000000" height="12" width="5" ry="0" rx="0" y="27" x="47.5">
        <animate
          repeatCount="indefinite"
          begin="-0.5454545454545454s"
          dur="1s"
          keyTimes="0;1"
          values="1;0"
          attributeName="opacity"
        ></animate>
      </rect>
    </g><g transform="rotate(163.63636363636363 50 50)">
      <rect fill="#000000" height="12" width="5" ry="0" rx="0" y="27" x="47.5">
        <animate
          repeatCount="indefinite"
          begin="-0.45454545454545453s"
          dur="1s"
          keyTimes="0;1"
          values="1;0"
          attributeName="opacity"
        ></animate>
      </rect>
    </g><g transform="rotate(196.36363636363637 50 50)">
      <rect fill="#000000" height="12" width="5" ry="0" rx="0" y="27" x="47.5">
        <animate
          repeatCount="indefinite"
          begin="-0.36363636363636365s"
          dur="1s"
          keyTimes="0;1"
          values="1;0"
          attributeName="opacity"
        ></animate>
      </rect>
    </g><g transform="rotate(229.0909090909091 50 50)">
      <rect fill="#000000" height="12" width="5" ry="0" rx="0" y="27" x="47.5">
        <animate
          repeatCount="indefinite"
          begin="-0.2727272727272727s"
          dur="1s"
          keyTimes="0;1"
          values="1;0"
          attributeName="opacity"
        ></animate>
      </rect>
    </g><g transform="rotate(261.8181818181818 50 50)">
      <rect fill="#000000" height="12" width="5" ry="0" rx="0" y="27" x="47.5">
        <animate
          repeatCount="indefinite"
          begin="-0.18181818181818182s"
          dur="1s"
          keyTimes="0;1"
          values="1;0"
          attributeName="opacity"
        ></animate>
      </rect>
    </g><g transform="rotate(294.54545454545456 50 50)">
      <rect fill="#000000" height="12" width="5" ry="0" rx="0" y="27" x="47.5">
        <animate
          repeatCount="indefinite"
          begin="-0.09090909090909091s"
          dur="1s"
          keyTimes="0;1"
          values="1;0"
          attributeName="opacity"
        ></animate>
      </rect>
    </g><g transform="rotate(327.27272727272725 50 50)">
      <rect fill="#000000" height="12" width="5" ry="0" rx="0" y="27" x="47.5">
        <animate
          repeatCount="indefinite"
          begin="0s"
          dur="1s"
          keyTimes="0;1"
          values="1;0"
          attributeName="opacity"
        ></animate>
      </rect>
    </g><g></g></g
  ><!-- [ldio] generated by https://loading.io --></svg
>
